### ISSUE TITLE
GLOBAL: Reduce spacing after Headings

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#14]
There seems to be too much spacing after headings which means that there is equal spacing between the bottom of a paragraph of text and the next paragraph. Example: 
<img width="1387" alt="Screenshot 2021-03-09 at 21 40 47" src="https://user-images.githubusercontent.com/16238581/110542325-d193e800-8120-11eb-8204-b7f257ba24bd.png">

**Comment by oliverjam** [comment]
Each element has `margin-top` based on its font-size, which I hoped would be enough to ensure headings ended up with more space above than below (since headings are bigger). However lower-level headings are almost the same size as the body copy so this was a silly idea.

I can manually set larger spaces above headings so it's clear which paragraph relates to which heading.

**Comment by Jamchiller** [comment]
Yeah I think that works, as well as perhaps reducing the margin-top size across the board

**Comment by oliverjam** [comment]
Yeah sure. I think I made it big-ish to try and differentiate the headings/sections more 😅

**Comment by oliverjam** [comment]
Do you want the space above to still be larger for bigger (higher-level) headings? Or just the same across all heading levels?

**Comment by Jamchiller** [comment]
Ideally different across different heading levels
