### ISSUE TITLE
GLOBAL: Add captions for photos

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#17]
Would be ideal to have captions for photos, as on Medium. They are already in [this post ](https://jaredhill-v2.netlify.app/blog/redesigning-medicspot/) but don't show up.

**Comment by oliverjam** [comment]
Yeah in markdown the text in the first brackets of the image syntax is the alt text (which isn't shown visually—it's mainly for accessibility/if the image doesn't load). This is meant to be a description of the information communicated in the image (or nothing if the image is purely decorative). Whereas a caption is usually more contextual, like what the image is for/clarifying what it shows.

E.g. if you were posting a screenshot of a sunset you might have:

```html
<figure>
  <img src="beautiful-sunset.tiff" alt="The sky at sunset, showing bright streaks of red, pink and purple mixing with the fluffy long clouds across the horizon">
  <figcaption>Sunset over London, UK</figcaption>
</figure>
```

The `alt` communicates the visual info for people who can't otherwise see the image; the caption communicates relevant extra stuff for everyone.

I'm gonna be building a custom image component for you to use (to support full-width option etc), so it can definitely have a caption option too. Been using captions a bunch recently on my [new FAC platform](https://learn.foundersandcoders.com/workshops/css-layout/) and I think they're great.

So it'll probably work something like this:

```markdown
## My title

Blah blah normal markdown...

{% image "sunset.jpg", "The sky at sunset...", "Sunset over London, UK", "full-width" %}

blah blah some more normal markdown
```

**Comment by Jamchiller** [comment]
Wiiiicked yep makes sense. I'll aim to put in alt text as well as caption text to keep it accessible af
