### ISSUE TITLE
ABOUT: Callout text doesn't recognise italics

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#46]
I've tried to use italics using markdown in the callout on the About page, however, it doesn't seem to be recognising it. 

https://jaredhill.co/about/

**Comment by oliverjam** [comment]
Ah so there's a tiny bit of complexity there that I should have told you about.

The way the Markdown parser knows what's Markdown vs what to treat as HTML is whether there are line breaks 😅 .

e.g.

```md
{% callout %}Some _text_ here{% endcallout %}
```

this will be output as-is into the Markdown document, like this:

```md
<p class="font-size-large">Some _text_ here</p>
```

Markdown can't parse HTML like that, so it just passes it straight through untouched.

If you want it to treat the content as Markdown you need a line break on either side, like this:

```md
{% callout %}

Some _text_ here

{% endcallout %}
```

This will output into the Markdown document like:

```html
<p class="font-size-large">

Some _text_ here

</p>
```

The Markdown parser will then convert the content since it can access it separately to the HTML, so the final output on the page will be:

```html
<p class="font-size-large">
  Some <em>text</em> here
</p>
```

**Comment by Jamchiller** [comment]
I'm really confused now, I created a branch and tried putting line breaks in as well as `_` around the word, but neither worked. It seemed like putting in more line breaks between the `{% endcallout %}` and text actually removed the large text styling...

**Comment by oliverjam** [comment]
Ah I see what's happening. First sorry you can use underscores or single-asterix for italics in Markdown.

So Markdown renders lines of text inside paragraph tags by default. However `{% callout %}` also tries to render a paragraph tag. So it's doubling up, getting confused and you're ending up with an empty `<p class="large"></p>` followed by the text in a normal size para.

Lemme try and fix
