### ISSUE TITLE
BLOG POST: Add spacing around images

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#57]

**Comment by oliverjam** [comment]
Turns out this is harder than expected if you wanna keep using markdown images (e.g. `![](./image.jpg`), since markdown insists on wrapping everything in a paragraph. So you end up with

```html
<p>A normal paragraph<p>
<p>
  <img src="/image.jpg">
</p>
```

So there's no easy way to distinguish the paragraph containing an image from a normal one.

This will be trivial to do once there's a [custom image component](#66), since then I will fully control the final markup.

**Comment by Jamchiller** [comment]
This custom image component is gonna be epic!
