### ISSUE TITLE
Make all external links open in new tab

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/jaredhill-v2#62]
Will go through and flag these

**Comment by oliverjam** [comment]
Ha this is kinda hard to automate. I guess if it's an "enhancement" I could use JS to read all the links on the page, check if they are external, then add the `target="_blank"` thing.

That way you can just write normal links and not worry about where they go.

Do you want one of those little "external" icons too?

<img width="155" alt="Screenshot 2021-04-07 at 10 45 26" src="https://user-images.githubusercontent.com/9408641/113846439-5e68aa80-978e-11eb-8b0c-b9040a9fc287.png">

**Comment by Jamchiller** [comment]
No worries, was more of a note to myself, there's not that many links so no need to automate. I just gotta go through and identify them, and maybe I can just flag to you so you can chuck in the code? Only reason I don't do it myself is because last time I broke the site trying to do it.

**Comment by oliverjam** [comment]
You shouldn't need to manually identify the links. Since presumably all the internal ones will be relative (e.g. `[my other post](/blog/my-other-post)` in markdown) I can just find any link pointing to a URL that starts with `http`.

If we want to be extra safe I could even explicitly check that the domain the link goes to is not jaredhill.co (if e.g. you wanted to use absolute links in your markdown like `[my other post](https://jaredhill.co/blog/my-other-post)`).

**Comment by Jamchiller** [comment]
That would be awesome. Saves me work!

**Comment by Jamchiller** [comment]
This looks like it worked for all of the links in posts, nice! The only ones I noticed still don't do this are the social links in the top right. Could these open externally too?

**Comment by oliverjam** [comment]
Oh yeah sure, my change was just for links in content, not the UI. Will update them now
